version: '3'

services:

  node:
    container_name: NFP-119-API-Tasks-node
    build: .
    working_dir: /usr/src/app
    command: npm start
    ports:
      - '8080:8080'
    volumes:
      - ./app:/usr/src/app

  mongo:
    container_name: NFP-119-API-Tasks-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mdproot

  mongo-express:
    container_name: NFP-119-API-Tasks-mongo-express
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mdproot
      ME_CONFIG_MONGODB_URL: mongodb://root:mdproot@mongo:27017/