version: '3'

services:
  node:
    container_name: container-node-NFP-119
    image: node:19.7-alpine3.16
    working_dir: /usr/src/app
    command: tail -f /dev/null
    ports:
      - '8080:8080'
    volumes:
      - ./app:/usr/src/app