version: '3'

services:

  node:
    build: .
    working_dir: /usr/src/app
    # Commande pour garder le container occuper pour qu'il reste ouvert
    # La commande peut etre remplacee par nodemon s'il est mis en place
    command: tail -f /dev/null
    ports:
      - '8080:8080'
    volumes:
      - ./app:/usr/src/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mdproot

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mdproot
      ME_CONFIG_MONGODB_URL: mongodb://root:mdproot@mongo:27017/